# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aj < Formula
  desc "Background JIT compiler for autonomous coding agents"
  homepage "https://github.com/agent-jit/AgentJIT"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.1.9/aj_0.1.9_darwin_amd64.tar.gz"
      sha256 "b23d27ebba381dc52d934a5cf74a82edf6a192cf01b5025eb4452187dbf30f67"

      define_method(:install) do
        bin.install "aj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.1.9/aj_0.1.9_darwin_arm64.tar.gz"
      sha256 "c4a6aa8abc59e1c0cc8ffa9e0579743f25e5358025caceaf232b133ba005eaf7"

      define_method(:install) do
        bin.install "aj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.1.9/aj_0.1.9_linux_amd64.tar.gz"
      sha256 "ee95b8d88bd9c30e94530d257af10f41e9a1f3635aefa66ed0efd56157491536"
      define_method(:install) do
        bin.install "aj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.1.9/aj_0.1.9_linux_arm64.tar.gz"
      sha256 "093f01a68842a8c1107d0dfbeb8a3dd92307878edf1564a4f93ac3c1b148c96b"
      define_method(:install) do
        bin.install "aj"
      end
    end
  end
end
