# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aj < Formula
  desc "Background JIT compiler for autonomous coding agents"
  homepage "https://github.com/agent-jit/AgentJIT"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.2.0/aj_0.2.0_darwin_amd64.tar.gz"
      sha256 "c568cb2218ce56a062621cb935c66590697712e362fa38f61848b1231956a285"

      define_method(:install) do
        bin.install "aj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.2.0/aj_0.2.0_darwin_arm64.tar.gz"
      sha256 "2bdf9c99f1e8edf239665cb0d625b21426959fbe1378b48d61aaf107129462b2"

      define_method(:install) do
        bin.install "aj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.2.0/aj_0.2.0_linux_amd64.tar.gz"
      sha256 "50d097e764bf60fd2bce6d41afb1f61b5fcb7a46b88d7b595fe3f7aa3c020597"
      define_method(:install) do
        bin.install "aj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-jit/AgentJIT/releases/download/v0.2.0/aj_0.2.0_linux_arm64.tar.gz"
      sha256 "24db03cc78e107d204da50911ba956c044f22c984a5a1fa704e136c027457bea"
      define_method(:install) do
        bin.install "aj"
      end
    end
  end
end
